spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000


  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB


  task:
    execution:
      pool:
        core-size: 10  #10 idle threads (Minimum)
        max-size: 50   #grow to 50 if needed
        queue-capacity: 1000 # queue


file:
  upload:
      dir: uploadedFiles
  convert:
      dir: convertedFiles


rabbitmq:
  queue:
    json:
      name: doc-conversion-json-queue
  exchange:
    name: doc-conversion-exchange
  routing:
    json:
      key: doc-conversion-json-key