name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be healthy
        run: sleep 30 # Adjust as necessary or implement a better health check

      - name: Run unit tests for doc-conversion
        run: docker-compose run --rm doc-conversion-test

      - name: Run unit tests for doc-conversion-gateway
        run: docker-compose run --rm doc-conversion-gateway-test


      - name: Shutdown Docker Compose
        run: docker-compose down
