name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run services
        run: |
          docker-compose -f docker-compose up -d

      - name: Run tests
        run: |
          docker-compose -f docker-compose run doc-conversion ./run_tests.sh+%s)
